reactor/BlockHound

- LICENSE
- agent/src/main/java/reactor/BlockHound.java
- agent/src/main/java/reactor/BlockHoundRuntime.java
- agent/src/main/java/reactor/BlockingMethod.java
- agent/src/main/java/reactor/InstrumentationUtils.java
- agent/src/main/java/reactor/blockhound/integration/BlockHoundIntegration.java
- agent/src/main/java/reactor/blockhound/integration/LoggingIntegration.java
- agent/src/main/java/reactor/blockhound/integration/ReactorIntegration.java
- agent/src/main/java/reactor/blockhound/integration/RxJava2Integration.java
- agent/src/main/java/reactor/blockhound/integration/util/TaskWrappingScheduledExecutorService.java
- example/src/test/java/com/example/BuilderTest.java
- example/src/test/java/com/example/FalseNegativesTest.java
- example/src/test/java/com/example/ReactorTest.java
- example/src/test/java/com/example/RxJavaTest.java
- native-agent/src/main/cpp/agent.cpp
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
https://www.apache.org/licenses/ ([https](https://www.apache.org/licenses/) result 200).
https://www.apache.org/licenses/LICENSE-2.0 ([https](https://www.apache.org/licenses/LICENSE-2.0) result 200).
> URL Cleanup

- agent/build.gradle
On Windows the binary gets packaged as `BlockHound.dll` instead of `libBlockHound.dll`.
Fixes gh-14
> Fixes the Windows binary name

- native-agent/CMakeLists.txt
Statically link mingw binaries for Windows library.
Fixes https://github.com/reactor/BlockHound/pull/16#issuecomment-475625391
> Statically link mingw binaries for Windows build

- agent/src/main/java/reactor/blockhound/ASMClassFileTransformer.java
- agent/src/main/java/reactor/blockhound/BlockHound.java
- agent/src/main/java/reactor/blockhound/BlockHoundRuntime.java
- agent/src/main/java/reactor/blockhound/BlockingMethod.java
- agent/src/main/java/reactor/blockhound/InstrumentationUtils.java
- agent/src/main/java/reactor/blockhound/integration/BlockHoundIntegration.java
- agent/src/main/java/reactor/blockhound/integration/LoggingIntegration.java
- agent/src/main/java/reactor/blockhound/integration/ReactorIntegration.java
- agent/src/main/java/reactor/blockhound/integration/RxJava2Integration.java
- docs/how_it_works.md
- example/src/test/java/com/example/BuilderTest.java
- example/src/test/java/com/example/FalseNegativesTest.java
- example/src/test/java/com/example/ReactorTest.java
- example/src/test/java/com/example/RxJavaTest.java
- junit-platform/src/main/java/reactor/blockhound/junit/platform/BlockHoundTestExecutionListener.java
- native-agent/src/main/cpp/agent.cpp
To be more Jigsaw friendly, we should clearly define the top level package for each Reactor's sub-project.
`reactor.BlockHound` class breaks this, and should be moved to a dedicated package (`reactor.blockhound`)
See https://github.com/reactor/reactor/issues/667
> Change the top-level package to `reactor.blockhound`.

- agent/build.gradle
- agent/src/main/java/reactor/blockhound/integration/ReactorIntegration.java
- example/build.gradle
Since https://github.com/reactor/reactor-core/pull/1682 is merged now, we should not instrument Reactor because it natively integrates with BlockHound via the SPI
> Skip `ReactorIntegration` on Reactor 3.3.x since it got a built-in one

- agent/src/main/java/reactor/blockhound/ASMClassFileTransformer.java
- agent/src/main/java/reactor/blockhound/BlockHound.java
- agent/src/main/java/reactor/blockhound/BlockHoundRuntime.java
- agent/src/main/java/reactor/blockhound/InstrumentationUtils.java
- example/src/test/java/com/example/CustomBlockingMethodTest.java
1. fix double loading of BlockHoundRuntime class
2. use `Class#getName` instead of `Class#getCanonicalName` (D'oh!)
3. add a test for a non-bootstrap blocking method
Fixes #39
> Fix custom blocking methods

- agent/src/main/java/reactor/blockhound/BlockHoundRuntime.java
- benchmarks/build.gradle
- native-agent/src/main/cpp/agent.cpp
This PR is a follow up of #35.
Since the non-blocking thread marker is immutable, we could store it in a `ThreadLocal` variable to avoid doing the native code switch.
Before:
```
Benchmark                                                Mode  Cnt  Score   Error  Units
BlockHoundBenchmark.measureAllowedBlockingCall           avgt    9  2,878 ± 0,096  us/op
BlockHoundBenchmark.measureBlockingCallInBlockingThread  avgt    9  0,822 ± 0,035  us/op
```
After:
```
Benchmark                                                Mode  Cnt  Score   Error  Units
BlockHoundBenchmark.measureAllowedBlockingCall           avgt    9  2,618 ± 0,095  us/op
BlockHoundBenchmark.measureBlockingCallInBlockingThread  avgt    9  0,510 ± 0,017  us/op
```
Given the baseline of `0,495us/op`, the overhead of doing a …
> Use `ThreadLocal` instead of the tags to store the non-blocking marker

- agent/src/main/java/reactor/blockhound/BlockHoundRuntime.java
- agent/src/main/java/reactor/blockhound/InstrumentationUtils.java
`BlockHoundRuntime` must be public because it is injected into bootstrap ClassLoader and being accessed from the JDK classes later.
But we don't want the users to call it, since it should only be used from the instrumentation.
This change makes the original class internal and changes the visibility with ASM when we inject it into the bootstrap ClassLoader.
> hide BlockHoundRuntime from public API

- agent/build.gradle
- agent/src/jarFileTest/java/reactor/blockhoud/AbstractJarFileTest.java
- agent/src/jarFileTest/java/reactor/blockhoud/JarFileShadingTest.java
As seen in https://github.com/netty/netty/pull/9687, due to https://github.com/johnrengelman/shadow/issues/519, we have `reactor/shaded/META-INF/versions/9/module-info.class` file in the final JAR, although we thought that we excluded it.
This PR fixes a few related shading issues and adds the missing tests for the shadowed jar, so that we will never miss such issue again.
> Shading is the gift that keeps on giving

- README.md
- agent/src/main/java/reactor/blockhound/BlockHound.java
- agent/src/main/java/reactor/blockhound/BlockingOperationError.java
- docs/customization.md
- example/src/test/java/com/example/RxJavaTest.java
> Throw specific BlockingOperationError instead of Error

- agent/src/main/java/reactor/blockhound/BlockHound.java
- example/src/test/java/com/example/StackTraceTest.java
- example/src/test/java/com/example/StrackTraceTest.java
Since we instrument the blocking methods, we add more frames to the stack of the thrown exception. We could artificially remove them from the created `java.lang.Error` instance to not confuse the users with something they do not expect.
**Before:**
```
java.lang.Error: Blocking call! java.lang.Thread.sleep
at reactor.blockhound.BlockHound$Builder.lambda$new$0(BlockHound.java:196)
at reactor.blockhound.BlockHound$Builder.lambda$install$6(BlockHound.java:338)
at reactor.blockhound.BlockHoundRuntime.checkBlocking(BlockHoundRuntime.java:46)
at java.base/java.lang.Thread.sleep(Thread.java)
at com.example.StrackTraceTest.lambda$shouldHideInternalFrames$0(StrackTraceTest.java:41)
```
**After:**
```
java.lang.Error: Blocking call! java.lang.Thread.sleep
at …
```
> Hide BlockHound's own frame from the Error

- README.md
Since [RxJava have decided to not accept the BlockHound integration](https://github.com/ReactiveX/RxJava/pull/6692), we should clarify what users of the future versions of RxJava should do to enable BlockHound with RxJava.
If RxJava community decide to add an integration with BlockHound, I will update it accordingly.
> Clarify RxJava 3+ support

- agent/src/main/java/reactor/blockhound/AllowancesByteBuddyTransformer.java
- agent/src/main/java/reactor/blockhound/BlockHound.java
- agent/src/main/java/reactor/blockhound/BlockHoundRuntime.java
- agent/src/main/java/reactor/blockhound/InstrumentationUtils.java
- example/src/test/java/com/example/DynamicThreadsTest.java
At S1P, we discussed with @elizarov the possibility of adding BlockHound integration to Kotlin:
https://github.com/Kotlin/kotlinx.coroutines/issues/1031
One of the major blockers was a lack of an API to dynamically decide whether thread is blocking or non-blocking since, in Kotlin, they change it dynamically.
This PR adds a new API to mark thread as "dynamic", which means that the blocking check should call `threadPredicate` once again before reporting the blocking call.
Example usage:
```java
b.dynamicThreadPredicate(p -> p.or(DynamicThread.class::isInstance));
b.nonBlockingThreadPredicate(p -> p.or(thread -> {
return thread instanceof DynamicThread && ((DynamicThread) thread).isNonBlocking;
}));
```
where `DynamicThread#isNonBlocking` is a field that reflects the current "mode".
> Add dynamic predicate support (Kotlin, Scala, others)

- agent/src/main/java/reactor/blockhound/BlockHound.java
- agent/src/main/java/reactor/blockhound/TestThread.java
Since OpenJDK requires `-XX:+AllowRedefinitionToAddDeleteMethod` (see #33)
starting with Java 13, we should test that the instrumentation
was applied correctly and fail fast if not.
> Perform a smoke test after instrumenting the classes.

- agent/src/main/java/reactor/blockhound/BlockHound.java
- example/src/test/java/com/example/DynamicCurrentThreadTest.java
> Reset installer `Thread`'s state

- agent/build.gradle
- build.gradle
- gradle/publishing.gradle
- junit-platform/build.gradle
Since the switch to more recent version of Gradle, two issues have been introduced in the pom:
1. the `name` is wrong (doesn't pick up `project.description` from each submodule) - should be fixed by deferring the evaluation of `project.description` using `afterEvaluate` closure
2. the junit-platform submodule publishes module file, while agent doesn't - for now we'll avoid generating the module metadata file by disabling the relevant tasks
> Fix the pom: no module metadata, fix name and description

- agent/src/main/java/reactor/blockhound/BlockHound.java
> Document <clinit> special name in (dis)allowBlockingCallsInside

- .github/workflows/release.yml
- agent/build.gradle
- build.gradle
- junit-platform/build.gradle
This commit switches the target of GA release deployments from Bintray
to Sonatype OSS / Maven Central (triggering the creation of a staging
repository, but not the closure and promotion of said repository).
This will ensure releases can be performed past Bintray's sunset.
Since Maven Central requires signed artifacts, the `signing` plugin is
added to the mix. As a core Gradle plugin, it is trusted enough to have
access to the relevant secrets.
This change also relies on the `release` environment in GitHub having
additional secrets (GPG signing key+passphrase, Sonatype credentials).
> Deploy releases to SonatypeOSS (staging repo) instead of Bintray

- junit-platform/build.gradle
cc @bsideup. If you could locally review and double check all seem in order in generated artifacts, that would be awesome.
if all is good, I'll release 1.0.6.RELEASE next Monday.
> Ensure junit-platform has compile dep to blockhound in pom

- README.md
- agent/build.gradle
- agent/src/main/java/reactor/blockhound/AllowancesByteBuddyTransformer.java
- agent/src/main/java/reactor/blockhound/BlockingCallsByteBuddyTransformer.java
- docs/quick_start.md
This PR is an attempt to add support for JDK 18+ (18, 19, 20), by upgrading byte-buddy to the latest version which is 1.12.20.
Now, there is an incompatible change that has been made in byte-buddy `transform` method of the  `AgentBuilder.Transformer` interface, which is implemented by BlockHound. So, the PR adapts to the new signature of the transform method, which is now taking a `ProtectionDomain`parameter.
Note that you will still need to use the `-XX:+AllowRedefinitionToAddDeleteMethods` when using JDK13+:
For example, when using maven, you can add the following which will make sure tests are run using the flag:
```
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-surefire-plugin</artifactId>
<version>2.22.2</version>
<configuration> …
```
> Upgrade byte-buddy to version 1.12.21 for support of jdk 18+ versions

- agent/build.gradle
- agent/src/jarFileTest/java/reactor/blockhoud/JarFileShadingTest.java
- agent/src/main/java/reactor/blockhound/BlockHound.java
This PR adds `premain` method and manifest attribute, supporting the installation of the agent via `-javaagent=` JVM option.
> Add Premain-Class attribute

- agent/src/main/java/reactor/blockhound/BlockHound.java
- docs/quick_start.md
This PR updates the documentation for the new -javaagent JVM option introduced in #297 , and also applies
a cosmetic feedback that has been made in the odl #297 PR.
> Updated doc for -javaagent JVM option

- README.md
- docs/quick_start.md
- example/build.gradle
This commit replaces the outdated testCompile Gradle target with its
official replacement, testImplementation. This includes occurrences in
the documentation.
Fixes #234.
> Replace testCompile with testImplementation in build/docs

- docs/tips.md
This PR manually applies the old PR #112, which was created a long time ago and which can't be currently merged.
> Add uncaught exceptions to test method signature

- agent/src/main/java/reactor/blockhound/BlockingMethod.java
`BlockingMethod` is a field in `BlockingOperationError` and `Error` is serializable. Client-server systems commonly send exceptions around, this exception fails to serialize.
> Make BlockingMethod serializable

- agent/src/main/java/reactor/blockhound/integration/BlockHoundIntegration.java
- example/src/test/java/com/example/IntegrationOrderingTest.java
- example/src/test/resources/META-INF/services/reactor.blockhound.integration.BlockHoundIntegration
The BlockHound.loadIntegration() method is intented to control ordering of `BlockhoundIntegration.applyTo` calls with respect to other integrations plugins. So, loadIntegrations() first loads all SPI plugins from META-INF/services, then appends any optional plugins provided in the loadIntegration(...) arguments, and finally sort the list before invoking the plugins applyTo methods.
However, by default, the BlockhoundIntegration.compareTo is implemented like this:
default int compareTo(BlockHoundIntegration o) {
return 0;
}
So, let's say we have these integration plugins being loaded from META-INF/services/... using the BlockHound.loadIntegrations() method:
```java
public class I1 implements BlockHoundIntegration {
public void applyTo(BlockHound.Builder builder) {}
}
public class I2 …
```
> BlockhoundIntegration SPI plugins ordering

- docs/customization.md
- example/src/test/java/com/example/BlockingDisallowTest.java
This PR documents how to disallow blocking calls that are done from allowed blocking calls.
Also committed the junit test proposed by Simon (thanks).
Fixes #187
> Document how to disallow blocking calls inside allowed blocking calls

- benchmarks/build.gradle
When running the benchmark using the baseline (latest release of BlockHound) like this:
```sh
./gradlew --no-daemon benchmarks:jmh -PjmhTarget=baseline 
````
then the baseline version to use is hard coded in the benchmark build.gradle.
Now, for japicmp, we have introduced the baseline version in the gradle.properties (`compatibleVersion`).
Let's reuse this "compatibleVersion" project property from benchmark/gradle.properties, this will make a little bit easier the release process.
> Reuse compatibleVersion project property in benchmark build.gradle

- .github/workflows/snapshot.yml
- gradle.properties
Now the 1.0.7.RELEASE version has been published, we need to bump compatibleVersion from gradle.properties, as well as BLOCKHOUND_VERSION from snapshot.yml
> Post-release 1.0.7: bump compatibleVersion and BLOCKHOUND_VERSION

- .github/workflows/snapshot.yml
- gradle.properties
Post-release 1.0.8: bump compatibleVersion and BLOCKHOUND_VERSION
> Post-release 1.0.8

- agent/build.gradle
from PR #374 (where org.unbroken-dome.test-sets was upgraded to 4.1.0 version), the agent project does not build anymore when using java8, we need to revert to 4.0.0 version:
```
A problem occurred configuring project ':agent'.
> Could not resolve all files for configuration ':agent:classpath'.
> Could not resolve org.unbroken-dome.gradle-plugins:gradle-testsets-plugin:4.1.0.
Required by:
project :agent > org.unbroken-dome.test-sets:org.unbroken-dome.test-sets.gradle.plugin:4.1.0
> No matching variant of org.unbroken-dome.gradle-plugins:gradle-testsets-plugin:4.1.0 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.6' …
```
> Revert org.unbroken-dome.test-sets to 4.0.0 version

- agent/src/main/java/reactor/blockhound/NativeWrappingClassFileTransformer.java
Since JDK16, a new `@IntrinsicCandidate` annotation has been introduced; It indicates that an annotated method may be (but is not guaranteed to be) intrinsified.
For example, the native Unsafe.park method is annotated with it:
```
@IntrinsicCandidate
public native void park(boolean isAbsolute, long time);
```
So, when BlockHound is instrumenting a native method, it first renames the native method using a prefix.
For example, `Unsafe.park` is renamed to `Unsafe.$$BlockHound$$_park`
And then the origin method (Unsafe.park) is rewritten in order to delegate the call to the renamed method, but the origin method is also rewritten to be **non-native**, so we end up with something like this after instrumentation:
```
class Unsafe {
...
public native void  $$BlockHound$$_park(boolean isAbsolute, …
```
> Remove IntrinsicCandidate annotation on non-native delegate methods.

- agent/src/main/java/reactor/blockhound/BlockHound.java
- example/src/test/java/com/example/BlockingDisallowTest.java
- example/src/test/java/com/example/ReactorTest.java
Since JDK19, `java.lang.Thread`'s methods have changed to support virtual threads. Specifically, for non-virtual threads, `sleep(long)` invokes `sleep0(long)` and `yield()` invokes `yield0()`. Moreover, since JDK21, `sleep(long, int)` and `sleep(Duration)` directly call `sleep0(long)` as opposed to `sleep(long)`.
Now, to identify all blocking `java.lang.Thread` calls, BlockHound will flag invocations of `sleep0(long)` and `yield0()` as opposed to `sleep(long)` and `yield()` when running on JDK19 or greater.
Fixes #394.
> Flag inner `Thread` methods for JDK 19 and greater

- agent/src/main/java/reactor/blockhound/BlockHound.java
- agent/src/main/java/reactor/blockhound/InstrumentationUtils.java
using Blockhound with JDK 22 is not working, even when using "-XX:+AllowRedefinitionToAddDeleteMethods" option:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project jup: 
[ERROR] 
[ERROR] Please refer to /workspace/code/jup/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] java.util.ServiceConfigurationError: org.junit.platform.launcher.TestExecutionListener: Provider reactor.blockhound.junit.platform.BlockHoundTestExecutionListener could not be instantiated
[ERROR] org.apache.maven.surefire.api.util.SurefireReflectionException: …
```
> Fix instrumentation for Thread.sleep with jdk22

- .github/workflows/snapshot.yml
- gradle.properties
Post-release 1.0.9: bump compatibleVersion and BLOCKHOUND_VERSION
> Post-release 1.0.9

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
Workflows actions are using some deprecated versions, and they also are not using pinned SHA versions.
let's replace the following:
actions/checkout@v1 -> actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 (v4.1.1)
actions/setup-java@v1 -> actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 (v4.2.1)
note: when needing java 13 for setup-java, 'adopt' distribution is used because 'temurin' distribution does not support  java 13.
> Update Github Actions

- README.md
It doesn't render correctly on GitHub without this space.
> docs: Fix 😜 in README

- .github/workflows/snapshot.yml
- gradle.properties
Post-release 1.0.10: bump compatibleVersion and BLOCKHOUND_VERSION
> Post-release 1.0.10
